// The ? guide as data: short topics of key → what it does, with a few notes. Rendered by helpPane.tsx (topic list,
// aligned key column, search). Keep rows to one idea each; the full reference lives in docs/no-brainers.md.

export type HelpLine = {keys: string; text: string} | {note: string} | {heading: string};
export interface HelpTopic {title: string; lines: HelpLine[]}

const key = (keys: string, text: string): HelpLine => ({keys, text});
const note = (text: string): HelpLine => ({note: text});
const heading = (text: string): HelpLine => ({heading: text});

export const HELP_TOPICS: readonly HelpTopic[] = [
	{title: 'Start here', lines: [
		note('The session list on the left, the pane on the right: → steps in, ← or Esc back out. Keys mean the same on every screen: Enter opens, Space toggles, a adds, x removes, E opens your editor.'),
		key('n', 'New session: agent, name, Tab for the workspace (↑↓ a new worktree\'s base), Enter launches'),
		key('j k  ↑↓', 'Select a session (or type its number)'),
		key('Enter  o', 'Open it full screen: the agent, or what the tab shows (shell, Git, Dev); on Notes, edit them'),
		key('Ctrl+]', 'Back to Deckhand from full screen (Ctrl+Space works too)'),
		key('Tab  [ ]', 'Next / previous tab: Preview, Terminal, Git, Dev, Notes (Shift+Tab goes back too)'),
		key('b  W', 'Tasks: the repository\'s task list (n starts a session from one) / Worktrees: what is merged, delete them'),
		key('C  U', 'Settings / Agents: versions and updates (Enter updates, r re-checks)'),
		key('?', 'This guide (↑↓ or 1-9 pick a topic, / searches, Esc closes)'),
		key('q', 'Quit the UI (agents and the daemon keep running); everywhere else Esc goes back'),
	]},
	{title: 'Sessions', lines: [
		key('N', 'Sub-session of the selected one: clean, ⑂ a fork of it, or ↳ from its handoff (after H)'),
		key('x  X', 'Stop, asking first (and whether to delete its worktree) / force-stop at once; starting: cancel'),
		key('s  S', 'Resume an exited session (or retry a failed setup) / restart it with a fresh conversation'),
		key('Space', 'Mark done / not done (☑; any session, not the same as merged)'),
		key('m  M', 'Merge the worktree into this branch (see Git & PRs) / mark it merged without merging (✓)'),
		key('Backspace  A', 'Archive an exited session (on an archived one: remove it for good, asking first) / archive or unarchive any'),
		key('H', 'Export a Markdown handoff (notes, commits, changed files, diff stat) and open it'),
		note('A fork copies the conversation as saved then, not a turn in progress.'),
		note('Deleting a worktree on stop is blocked by uncommitted work or unpushed commits unless you type DELETE.'),
	]},
	{title: 'Find & organize', lines: [
		key('1-9  0', 'Select by number (0 is 10; with more than 10, type the number: Enter or a short pause selects, Esc clears)'),
		key('/', 'Search titles, notes, tasks, agent, branch and path (Enter keeps it, Esc clears)'),
		key('f', 'Filter menu: a active · r running · ! attention · e exited · A archived · * all; f f back to active (the sidebar header names any other)'),
		key('!', 'Next session that needs attention'),
		key('J K', 'Move the session down / up among its siblings'),
		key('c', 'Hide exited children → collapse → expand'),
		key('< >', 'Narrow / widen the sidebar'),
		key('R', 'Reload the list (it updates live; rarely needed)'),
	]},
	{title: 'Sidebar', lines: [
		note('A row: number, tree, status, title, then markers and the agent. Archived rows are dimmed (in the archived view: the parents shown for context).'),
		key('⠋ ● ◌ ○', 'Starting or working · idle · running, activity unknown · exited'),
		key('? ◆ ⌛', 'Needs input · response ended (not task success) · rate-limited'),
		key('!', 'Before the title: failed, or exited failed / interrupted'),
		key('▾ ▸', 'Has sub-sessions: expanded / collapsed (c)'),
		key('↳ ⑂', 'Clean / forked sub-session'),
		key('▶', 'Dev runs in this worktree (on its first row)'),
		key('▣ ✓ ☑', 'Archived · merged · done (Space; its title muted)'),
		key('! +N', 'After the title: cleanup error · N hidden sub-sessions'),
		key('✶ π ◇', 'Agent: Claude · Pi · Codex'),
		key('↑', 'Runs an older agent version than installed: restart it (x, then s) to update'),
		key('╎', 'Shares the selected session\'s worktree: Terminal, Git, Dev'),
		key('! N', 'Header: N sessions need attention (! jumps to them)'),
		note('Below the list: the selected session\'s full title, agent · state · age (both versions when ↑), branch or main checkout, then ╎N (N others share the worktree) ▶ ✓ ☑2d (done 2 days ago) ▣, ☐ N open checklist items.'),
	]},
	{title: 'Panes', lines: [
		key('p t g d a', 'Jump to Preview, Terminal, Git, Dev, Notes (d twice quickly also starts or stops Dev)'),
		key('→  l', 'Step into the pane: scroll the preview (running), browse Git changes, edit the notes'),
		key('←  h  Esc', 'Step back out to the session list'),
		key('v', 'On Terminal: switch between the shell and the last action'),
		key('E', 'Open in Cursor / VS Code: the note on Notes, otherwise the session\'s folder'),
		heading('Scrolling the preview (→)'),
		key('j k  ↑↓', 'Scroll (PgUp/PgDn a page, g/G top/bottom, the mouse wheel; + − change wheel speed)'),
		note('Agents ask for approvals in their own terminal: open it (Enter) to answer. Terminal, Git and Dev belong to the worktree: all its sessions share them, also after their agents exit.'),
	]},
	{title: 'Dev & actions', lines: [
		key('r', 'Run: Dev first (start or stop it), then your actions; Enter runs the selected one'),
		key('x', 'In the run list: stop the running action (or Dev)'),
		key('d  d d', 'The Dev tab (Enter opens it while it runs) / twice quickly: start or stop Dev'),
		note('Dev is shared by every session in the same worktree and keeps running after their agents exit, until stopped (or the worktree is deleted).'),
		note('An action runs in its own process beside the shell and Dev, one at a time per worktree, and shows on the Terminal tab (v: back to the shell); Enter opens it while it runs; its output and exit code stay until the next one.'),
		note('Set the Dev command, actions and a setup command for new worktrees in Settings (C).'),
	]},
	{title: 'Git & PRs', lines: [
		key('i', 'Workspace overview: branch, changes, diff size, base, upstream'),
		key('m', 'Merge / squash into this branch, uncommitted (Space: commit first, or tick a follow-up; conflicts: Enter keeps, x aborts)'),
		key('→  Enter', 'On the Git tab (the worktree\'s changes, VS Code style): browse them / open lazygit'),
		heading('Browsing changes (→; ← or Esc back; o opens lazygit)'),
		key('j k  ↑↓', 'Select a file (g/G or Home/End: first/last)'),
		key('Space', 'Stage it, or unstage it if staged (a staged conflict is resolved)'),
		key('a  A', 'Stage everything except conflicts / unstage everything'),
		key('Enter  E', 'Open it in Cursor / VS Code at its first change'),
		key('J K', 'Scroll its diff (Page Up/Down: a page)'),
		heading('Inside i (Esc closes; ↑↓, j k and PgUp/PgDn move through it)'),
		key('c', 'Create a PR: push the branch, then open GitHub\'s PR form (asks first)'),
		key('P', 'Fetch PR and check status (gh)'),
		key('b', 'Open the PR in the browser'),
		key('g', 'Open the Git tab'),
	]},
	{title: 'Settings', lines: [
		note('Two columns: Global (every repo) and This repo (deckhand.json in the main checkout; fine to commit). This repo wins.'),
		key('● ⚠', 'In effect / a repo value that applies once trusted ((built-in): Deckhand\'s default)'),
		key('j k  ← →', 'Setting / column (Tab too; PgUp/PgDn, Home/End jump)'),
		key('Enter  x', 'Edit / clear the cell (Actions: a adds, x removes; Linked items: Space, Enter saves)'),
		key('E  T', 'The column\'s raw JSON (Ctrl+S saves, Ctrl+F formats) / review and trust the repo file'),
		note('A repo\'s commands only run once you trust it; you\'re asked right before. Your edits here keep it trusted.'),
		heading('Agent signals (Settings → Agents; on for Claude unless switched off)'),
		note('Sessions report working, needs input, done, failed or rate-limited (! jumps to them) and what they wait on (a question, a plan, a command, their last line), and can notify you. Claude needs nothing; Codex: switch on, then `deckhand hooks codex` in ~/.codex/hooks.json; Pi has none. "Done" means it stopped, not that it succeeded.'),
	]},
	{title: 'Tasks', lines: [
		note('One list per repository. On a worktree: ◆ the task it was started for (its note\'s checklist under it as steps, 2/5), ☐ a follow-up. A note checkbox becomes a task only when you send it.'),
		key('b  v', 'The board: a group per worktree with open tasks, backlog, done / only the selected session\'s worktree'),
		key('a  Enter', 'Add (to the selection\'s group) / edit: Enter saves the title, Tab adds details (Ctrl+S saves); on a step, open its note'),
		key('n  w', 'Start a session for it in a new worktree (↑↓ picks the base) / move it: backlog, back to its note, a worktree or session (Tab, type to search)'),
		key('Space  x', 'Tick or reopen (a step: in its note) / delete (x twice)'),
		key('o  J K', 'Open the session doing it / reorder (j k, g G move)'),
		key('Tab  E', 'Every note by worktree (a sends an item, A all its open ones, Enter opens it, f only open items) / the list in your editor'),
		note('A merge ticks ◆ and sends open ☐ to the backlog unless m ticked them; done ticks ◆; undoing either undoes that. Work removed unmerged, and its note\'s open items when m, x or W end it (Space keeps them), go to the backlog.'),
	]},
	{title: 'Notes', lines: [
		note('A worktree has one note, shared by its sessions; a main-checkout session has its own and the main checkout\'s. Autosaved Markdown; removed notes go to notes/trash.'),
		key('Enter  →', 'Edit (Esc finishes); E opens the note in Cursor / VS Code'),
		key('Tab', 'Main checkout: switch between this session\'s note and the shared one'),
		key('Ctrl+X', 'Check / uncheck the line\'s item, or make the line a - [ ] item'),
		key('Ctrl+T', 'New checklist item below (Enter on an item continues the list)'),
		key('Alt+← →', 'Jump a word (Ctrl+←→, Alt+B/F too); Alt+Backspace or Ctrl+W deletes one, Alt+Delete the next'),
		key('Ctrl+A  E', 'Start / end of the line (Home / End too; Ctrl+Home/End: the note; PgUp/PgDn a screen)'),
		key('Ctrl+P', 'Send the line\'s checklist item to Tasks (the note keeps a ↗ link)'),
		key('Ctrl+O', 'Open the note you are editing in Cursor / VS Code'),
		note('☐ N open below the sidebar counts open items of both notes. A worktree\'s note goes when its last session is removed (removing asks first; Enter sends open items to Tasks).'),
	]},
	{title: 'Worktrees', lines: [
		note('W lists every worktree of the repository (Deckhand\'s or not) by what to do with it: merged and safe to delete, merged with leftovers, in progress, idle (nothing running for 14 days), missing (directory gone), and the main checkout.'),
		key('x', 'Delete it, asking first: keep or delete its branch; its running sessions are stopped first (named before you confirm)'),
		key('x', 'On the "Merged · safe to delete" heading: delete all of them and their branches, one confirmation'),
		key('Enter  o', 'Select its session in the sidebar'),
		key('M  E', 'Mark it merged or clear the marker / open it in your editor'),
		key('R  j k  g G', 'Check them all again / move'),
		note('Same safety as x on a session: uncommitted work or commits only on the branch need DELETE typed; the main checkout and the one this Deckhand runs in are never deleted. Its sessions are archived afterwards (f A shows them).'),
	]},
];
